name: Greet user

on:
  push:
    branches:
      - main

jobs:
  greet_user_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello there
        run: |
          echo "Hello there!"

  greet_user_by_name_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello to user using user's name
        run: |
          echo "Hello ${{ github.actor }}!"
